### ISSUE TITLE
WP v. 4.3 vs ACT

### ISSUE THREAD

**Issue by Grazouillis** [fmarzocca/List-all-posts-by-ACT#2]
Hello Fabio,

Do you know that your plugin ACT list hasn't been working since the last version of Wordpress (4.3) ?

No result with this shortcode : [ACT-list show='Category' singleuser=1 exclude='non-classe']. 
Only the categories titles appear on my website...

Best regards.

**Comment by fmarzocca** [comment]
Hi Marecages,

I'm sorry to hear that, I have just tried your exact syntax (with a diferent class name, of course) and it is perfectly working in WP 4.3.

Do you have any PHP error in your server's Apache log?

By removing the category exclusion, are your posts showing?

**Comment by Grazouillis** [comment]
Thanks a lot for your quick answer.
Unlucky, it doesn't work with the shortcode [ACT-list] only. Here is the page with the "table of content" which is generated by ACT : http://marecages.be/toc/ (updated with [ACT-list])
There is no error in my server's Apache log about this specific page.

A friend noticed the same problem with his worpress 4.3 : his list is empty too !

**Comment by fmarzocca** [comment]
Hi,

I will have a deeper look, even if my 3 different sites are all working.

Pls let me know:
- which is your plugin version?
- which is the php version?

Il domenica 6 settembre 2015, Marecages notifications@github.com ha
scritto:

**Comment by fmarzocca** [comment]
This is the best site which is using the plugin (WP 4.3):

http://www.atopon.it/indice-degli-articoli

**Comment by fmarzocca** [comment]
Don't you have a clean WP 4.3 install to test the plugin on? I am suspecting some interference with other plugins or theme..
The code is quite straight-forward but I keep debugging.

**Comment by fmarzocca** [comment]
How are you setting up those strange subcategory names? (i.e. ***\* | J'AI
SAVOURÉ) What are those trailing asterisk and the "pipe" symbol? Are they
part of the subcategory name?

**Comment by fmarzocca** [comment]
Marecages, pls be aware that if your site includes only administrator's posts, you'll have no output if you just type [ACT-list] because administrator's posts are NOT included by default. Pls use the shortcode generator in the Tools section of your web's admin. You need at least to add "singleuser=1"

**Comment by Grazouillis** [comment]
The plugin version is the last one : 2.2
My php version is 5.4

The name of my categories are weird but they worked with the previous version of ACT.
The stars are some evaluations * -dislike to *****-adore. It was my solution to have a croissant order of my appraisals. I can change that to see if it work again.
I will desactivate the other plugins to see if there are some incompatibilities / interferences or install a new Wordpress 4.3 in local.

[ACT-list show='Category' singleuser=1 exclude='non-classe'] was the shortcode I used previously. It doesn't work currently.
[ACT-list singleuser=1] neither.

I come back to you with the several tests you purpose !

**Comment by Grazouillis** [comment]
You were right, there were some interferences with the plugin "TypoFR".
Thanks a lot for your help and apologizes for the annoyance !
:-)

**Comment by fmarzocca** [comment]
I am glad you fixed this!
