### ISSUE TITLE
Shortcode Does Not Generate

### ISSUE THREAD

**Issue by johncourtland** [fmarzocca/List-all-posts-by-ACT#6]
Good day, please see screenshot, for the items selected, the short code does not generate, the graphic wheel spins indefinitely. Any help or direction is greatly appreciated. Thank you
WP V6.4.3 PHP 8.1
![ACT Error](https://github.com/fmarzocca/List-all-posts-by-ACT/assets/12961228/cb31e99a-4884-42c4-802c-51d055329e67)

**Comment by fmarzocca** [comment]
Cannot confirm the issue. I have tested on many sites and it is working. Have you tried to change the Category to be shown (instead of "-- American Woods")?
What version of  plugin are you using?

**Comment by johncourtland** [comment]
Thank you for looking Fabio, the plugin generates shortcode if I include all categories, but if I exclude just one category with the other variables set to default, the short code is generated. If there is a way I can send my login credentials to you for my test instance of WP, you could see what I am seeing?

**Comment by johncourtland** [comment]
Fabio, I switched to php 7.4 and the short code generator works, it does not seem to perform with php 8.0 and above.

**Comment by fmarzocca** [comment]
Thank you. I have no chance to test on php 8.x
Could you pls send your server's log when the issue occurs?

**Comment by fmarzocca** [comment]
Which version of the plugin are you running?

**Comment by fmarzocca** [comment]
This has been fixed in v.2.8.1
Pls update plugin
